#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= commandline

# The file name of the executable
TARGET	:= hang

# If the K3_ROOT environment variable is set, you can comment out the following line

# Include the Makefile
include ../Makefile.include
