#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= commandline khepera3 i2cal

# The file name of the executable
TARGET	:= motor_initialize

# Include the Makefile
include ../Makefile.include
