#
# (c) 2006 - 2008 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

# The list of modules that this program needs
MODULES	:= commandline

# The file name of the executable
TARGET	:= udp_receiver

# Include the Makefile
include ../Makefile.include
